import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import net from 'node:net';
let child,base,temp;
before(async()=>{
  temp=await mkdtemp(join(tmpdir(),'terrawatch-test-'));const probe=net.createServer();await new Promise(resolve=>probe.listen(0,'127.0.0.1',resolve));const port=probe.address().port;await new Promise(resolve=>probe.close(resolve));base=`http://127.0.0.1:${port}`;
  child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port),HOST:'127.0.0.1',DATABASE_PATH:join(temp,'test.sqlite'),DISABLE_POLL:'1',DEMO_ROADS:'synthetic',GEMINI_API_KEY:'',ELEVENLABS_API_KEY:'',TIGER_DATABASE_URL:'',DATABRICKS_INGEST_URL:''},stdio:['ignore','pipe','pipe']});
  await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Test server did not start')),10000);child.stdout.on('data',d=>{if(d.toString().includes('TerraWatch running')){clearTimeout(timeout);resolve();}});child.on('error',reject);child.on('exit',code=>{if(code)reject(new Error(`Test server exited ${code}`));});});
});
after(async()=>{if(child&&child.exitCode===null){const exited=new Promise(resolve=>child.once('exit',resolve));child.kill();await exited;}if(temp){assert.ok(temp.startsWith(join(tmpdir(),'terrawatch-test-')),'Cleanup must stay inside the test-created temporary directory');await rm(temp,{recursive:true,force:true});}});
async function post(path,body,extra={}){return fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',...extra},body:JSON.stringify(body)});}
test('serves application shell with CSP and health status',async()=>{const health=await fetch(base+'/api/health');assert.ok((await health.json()).ok);const shell=await fetch(base+'/');assert.equal(shell.status,200);assert.match(shell.headers.get('content-security-policy'),/default-src 'self'/);assert.match(await shell.text(),/TerraWatch/);});
test('validates mode and region and keeps server files private',async()=>{assert.equal((await fetch(base+'/api/snapshot?mode=fake')).status,400);assert.equal((await fetch(base+'/api/snapshot?region=__proto__')).status,400);assert.equal((await fetch(base+'/.env')).status,404);assert.equal((await fetch(base+'/server.mjs')).status,404);});
test('demo snapshot and route endpoint perform a complete planning workflow',async()=>{const s=await(await fetch(base+'/api/snapshot?mode=demo')).json();assert.equal(s.stats.alerts,3);assert.equal(s.mode,'demo');assert.equal(s.roads,undefined);const r=await post('/api/route',{mode:'demo',region:'raleigh',start:[s.region.center[0]-.036,s.region.center[1]-.012],destinationId:s.facilities[0].id});assert.equal(r.status,200);const route=await r.json();assert.ok(route.distanceKm>0);assert.ok(route.excludedSegments>0);assert.equal(route.geometry.type,'LineString');});
test('report endpoint rejects invalid coordinates and stores unverified app-local observations',async()=>{const body={region:'raleigh',mode:'demo',kind:'blocked_road',coordinates:[-78.69,35.79],description:'Test observation: branch across a scenario road.'};assert.equal((await post('/api/reports',{...body,coordinates:[0,0]})).status,400);assert.equal((await post('/api/reports',{...body,description:'x'})).status,400);const r=await post('/api/reports',body);assert.equal(r.status,201);const report=await r.json();assert.equal(report.status,'unverified');const snapshot=await(await fetch(base+'/api/snapshot?mode=demo')).json();assert.equal(snapshot.reports.length,1);const other=await(await fetch(base+'/api/snapshot?mode=demo&region=wilmington')).json();assert.equal(other.reports.length,0);});
test('rejects cross-origin mutations and non-JSON writes',async()=>{assert.equal((await post('/api/brief',{mode:'demo'},{Origin:'https://evil.example'})).status,403);assert.equal((await fetch(base+'/api/brief',{method:'POST',body:'{}'})).status,415);});
test('briefing is usable without secrets and optional audio is honestly unavailable',async()=>{const r=await post('/api/brief',{mode:'demo'});assert.equal(r.status,200);const b=await r.json();assert.equal(b.ai,false);assert.ok(b.id);assert.equal((await post('/api/audio',{mode:'demo',briefId:b.id})).status,503);const config=await(await fetch(base+'/api/config')).json();assert.equal(config.integrations.gemini.configured,false);assert.equal(config.integrations.elevenlabs.configured,false);});
test('offline pack includes local graph and shared routing module is served',async()=>{const pack=await(await fetch(base+'/api/offline?mode=demo')).json();assert.ok(pack.roads.nodes.length>0);assert.equal((await fetch(base+'/shared/routing.mjs')).status,200);assert.equal((await fetch(base+'/shared/store.mjs')).status,404);});
test('SSE sends a connected event without fabricated sensor observations',async()=>{const controller=new AbortController(),r=await fetch(base+'/api/stream?region=raleigh',{signal:controller.signal});assert.equal(r.headers.get('content-type'),'text/event-stream');const reader=r.body.getReader();let message='';while(!message.includes('event: connected')){const value=await reader.read();message+=new TextDecoder().decode(value.value);}assert.match(message,/"pollMs":60000/);assert.ok(!message.includes('gage_height'));controller.abort();});

test('personal evacuation endpoint suggests resources for one disaster at a time',async()=>{const s=await(await fetch(base+'/api/snapshot?mode=demo&region=wilmington')).json();for(const hazard of ['flood','hurricane','heat']){const response=await post('/api/evacuate',{region:'wilmington',mode:'demo',hazard,start:s.demoOrigins[hazard]});assert.equal(response.status,200);const plan=await response.json();assert.equal(plan.status,'routes_found');assert.equal(plan.originInside,true);assert.equal(plan.hazard,hazard);assert.equal(plan.mapSnapshot.roads,undefined);assert.equal(plan.mapSnapshot.mode,'demo');assert.equal(plan.mapSnapshot.roadInfo.basis,'synthetic');assert.ok(plan.alternatives.every(r=>plan.mapSnapshot.facilities.some(f=>f.id===r.destination.id)));assert.equal(plan.alternatives[0].comparison.status,'available');assert.equal(plan.alternatives.length,3);assert.deepEqual(plan.otherHazardsChecked,[]);}});
test('personal evacuation validates user choices and serves shared offline logic',async()=>{assert.equal((await post('/api/evacuate',{mode:'demo',hazard:'all',start:[-78.6382,35.7796]})).status,400);assert.equal((await post('/api/evacuate',{mode:'demo',hazard:'flood',start:[0,0]})).status,400);assert.equal((await fetch(base+'/shared/evacuation.mjs')).status,200);});
test('personal briefing only explains the selected demo disaster',async()=>{const response=await post('/api/brief',{mode:'demo',hazard:'flood'});const b=await response.json();assert.equal(response.status,200);assert.match(b.text,/flood guidance/);assert.ok(!b.text.includes('Tropical storm warning'));assert.ok(!b.text.includes('Extreme heat warning'));});

test('custom flood coordinates route through the API without the example-location button',async()=>{const r=await post('/api/evacuate',{mode:'demo',region:'raleigh',hazard:'flood',start:[-78.62016,35.79015],destinationId:'demo-raleigh-f6'});assert.equal(r.status,200);const p=await r.json();assert.equal(p.status,'routes_found');assert.equal(p.originInside,true);assert.equal(p.alternatives[0].destination.id,'demo-raleigh-f6');assert.ok(p.alternatives[0].snapDistances.start<.01);const s=await(await fetch(base+'/api/snapshot?mode=demo')).json();assert.equal(s.demoRouting.version,2);assert.equal(s.demoRouting.floodedAreas.features.length,2);});
