import { test, expect } from '@playwright/test'
test.beforeEach(async({request})=>{await request.post('/api/demo',{data:{action:'reset'}})})

test('map, relief, route evidence, cached mode and new-hazard reroute',async({page},info)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await expect(page.getByText('DEMO MODE',{exact:true})).toBeVisible()
  await expect(page.getByRole('region',{name:/Route map/})).toBeVisible()
  await expect(page.getByText('Official cooling center',{exact:true})).toBeVisible()
  await expect(page.getByText('Potential relief location',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Compare routes'}).click()
  await expect(page.getByText('0.90 km',{exact:true})).toBeVisible()
  await expect(page.getByText('1.10 km',{exact:true})).toBeVisible()
  await page.getByText('Why this route?',{exact:true}).click()
  await expect(page.getByText('Excessive Heat Warning',{exact:true})).toBeVisible()
  await page.screenshot({path:`test-results/${info.project.name}-route.png`,fullPage:true})
  await page.getByRole('button',{name:'Simulate offline'}).click()
  await expect(page.getByText('OFFLINE',{exact:true})).toBeVisible()
  await expect(page.getByText('1.10 km',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Reconnect + new hazard'}).click()
  await expect(page.getByText('1.30 km',{exact:true})).toBeVisible()
  await expect(page.getByText(/Route updated · a new hazard/)).toBeVisible()
  expect(errors).toEqual([])
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})

test('installed shell reloads with backend and network unavailable',async({page,context})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Compare routes'}).click()
  await expect(page.getByText('1.10 km',{exact:true})).toBeVisible()
  await page.evaluate(()=>navigator.serviceWorker.ready)
  await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true)
  const manifest=await page.evaluate(async()=>await (await fetch('/manifest.webmanifest')).json())
  expect(manifest.display).toBe('standalone')
  expect(manifest.icons.map((i:{sizes:string})=>i.sizes)).toContain('512x512')
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByText('1.10 km',{exact:true})).toBeVisible()
  await expect(page.getByText('OFFLINE',{exact:true})).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('Backend unavailable')
  await expect(page.getByRole('region',{name:/Route map/})).toBeVisible()
  const cachedUrls=await page.evaluate(async()=>{const names=await caches.keys();const cache=await caches.open(names.find(n=>n.startsWith('wayfinder-shell-'))!);return (await cache.keys()).map(r=>r.url)})
  expect(cachedUrls.some(url=>url.includes('/api/'))).toBe(false)
  await context.setOffline(false)
  await expect(page.getByText('1.30 km',{exact:true})).toBeVisible()
})

test('location denial has a coordinate fallback',async({page})=>{
  await page.addInitScript(()=>{navigator.geolocation.getCurrentPosition=(_success,error)=>error?.({code:1,message:'Denied',PERMISSION_DENIED:1,POSITION_UNAVAILABLE:2,TIMEOUT:3})})
  await page.goto('/')
  await page.getByRole('button',{name:'Use my location'}).click()
  await expect(page.getByRole('alert')).toContainText('Location permission was denied')
  await page.getByLabel('Latitude, longitude').fill('35.770, -78.640')
  await page.getByRole('button',{name:'Set',exact:true}).click()
  await expect(page.getByText('Entered coordinates',{exact:true})).toBeVisible()
})
